name: nadaushd
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_analytics: ^11.4.2
  flutter_native_splash: ^2.4.4
  firebase_auth: ^5.4.2
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.17

flutter_native_splash:
  color: "#000000"  # Background color (black)
  image: "assets/icon.png"  # Your app icon
  android_12:
    image: "assets/icon.png"
    color: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true


  assets:

    - assets/aura.png
  